'use client'
import { useState } from 'react'
import { ArrowDownRight, ArrowRight, Menu, Search, ShoppingBag, X } from 'lucide-react'

type Product = { name: string; type: string; price: string; image: string; tag?: string }
const products: Product[] = [
  { name: 'The Everyday Tee', type: 'Heavyweight cotton / Ink', price: '₹2,490', image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85', tag: 'New' },
  { name: 'Relaxed Overshirt', type: 'Organic twill / Bone', price: '₹4,990', image: 'https://images.unsplash.com/photo-1598808503746-f34c53b9323e?auto=format&fit=crop&w=900&q=85' },
  { name: 'Studio Trouser', type: 'Cotton linen / Stone', price: '₹4,490', image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=900&q=85', tag: 'Bestseller' },
  { name: 'Daily Short', type: 'Cotton poplin / Ink', price: '₹2,990', image: 'https://images.unsplash.com/photo-1565084888279-aca607ecce0c?auto=format&fit=crop&w=900&q=85' }
]

export default function Home() {
  const [menu, setMenu] = useState(false); const [cart, setCart] = useState<Product[]>([]); const [search, setSearch] = useState(false)
  const add = (p: Product) => setCart([...cart, p])
  return <main>
    <header className="fixed top-0 z-30 flex w-full items-center justify-between px-5 py-5 mix-blend-difference text-white md:px-10">
      <div className="flex items-center gap-8 text-[10px] uppercase tracking-[.24em]"><button className="md:hidden" onClick={() => setMenu(!menu)}><Menu size={18}/></button><nav className="hidden gap-7 md:flex"><a href="#about">About</a><a href="#shop">Shop</a><a href="#home">Home</a><a href="#journal">News</a></nav></div>
      <a href="#home" className="absolute left-1/2 -translate-x-1/2 text-xl font-bold tracking-[-.08em]">KESHEV</a>
      <div className="flex items-center gap-5 text-[10px] uppercase tracking-[.2em]"><button onClick={() => setSearch(!search)} aria-label="Search"><Search size={17}/></button><a className="hidden md:block" href="#account">Sign up / Log in</a><button onClick={() => setCart(cart)} className="flex items-center gap-2">Cart <span>({cart.length})</span></button></div>
    </header>
    {menu && <div className="fixed inset-0 z-20 flex flex-col justify-end bg-ink p-6 pb-12 text-white md:hidden"><button onClick={() => setMenu(false)} className="absolute right-6 top-6"><X/></button>{['About','Shop','Home','News','Account'].map(x => <a key={x} href={x === 'Shop' ? '#shop' : '#home'} onClick={() => setMenu(false)} className="border-b border-white/20 py-4 text-4xl tracking-tight">{x}</a>)}</div>}
    {search && <div className="fixed left-0 right-0 top-0 z-20 bg-cream px-6 pb-6 pt-24"><div className="flex items-center gap-3 border-b border-ink/30 pb-3"><Search size={20}/><input autoFocus placeholder="Search the collection" className="w-full bg-transparent text-2xl outline-none"/><button onClick={() => setSearch(false)}><X/></button></div></div>}
    <section id="home" className="relative flex min-h-[92vh] items-end overflow-hidden bg-ink px-5 pb-10 text-white md:px-10 md:pb-14"><div className="grain absolute inset-0 opacity-80"/><div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-black/10"/><div className="relative w-full"><p className="mb-7 text-[10px] uppercase tracking-[.28em]">Independent label · Est. 2024</p><h1 className="display max-w-5xl">Made for<br/><i className="font-serif font-normal">every</i> day.</h1><div className="mt-10 flex flex-wrap gap-3"><a href="#shop" className="flex items-center gap-8 bg-white px-5 py-3 text-[10px] uppercase tracking-[.2em] text-ink">Explore tops <ArrowRight size={15}/></a><a href="#bottoms" className="flex items-center gap-8 border border-white/70 px-5 py-3 text-[10px] uppercase tracking-[.2em]">Explore bottoms <ArrowRight size={15}/></a></div></div></section>
    <section id="about" className="grid gap-12 px-5 py-24 md:grid-cols-[1fr_2fr] md:px-10 md:py-36"><p className="text-[10px] uppercase tracking-[.25em]">01 / The point of view</p><div><p className="max-w-3xl text-3xl leading-[1.08] tracking-[-.04em] md:text-6xl">A considered wardrobe for the everyday. <span className="text-black/35">No noise, no excess. Just pieces that get better with living in them.</span></p><a href="#journal" className="mt-10 inline-flex items-center gap-3 border-b border-ink pb-2 text-[10px] uppercase tracking-[.2em]">Read our story <ArrowDownRight size={15}/></a></div></section>
    <section id="shop" className="bg-[#dcd7ce] px-5 py-16 md:px-10 md:py-24"><div className="mb-10 flex items-end justify-between"><div><p className="mb-3 text-[10px] uppercase tracking-[.25em]">02 / The collection</p><h2 className="text-5xl tracking-[-.07em] md:text-8xl">Tops</h2></div><a href="#shop" className="hidden text-[10px] uppercase tracking-[.2em] md:block">View all +</a></div><ProductGrid items={products.slice(0,2)} onAdd={add}/></section>
    <section id="bottoms" className="px-5 py-16 md:px-10 md:py-24"><div className="mb-10 flex items-end justify-between"><div><p className="mb-3 text-[10px] uppercase tracking-[.25em]">03 / The collection</p><h2 className="text-5xl tracking-[-.07em] md:text-8xl">Bottoms</h2></div></div><ProductGrid items={products.slice(2)} onAdd={add}/></section>
    <section id="journal" className="grid min-h-[55vh] bg-ink px-5 py-16 text-white md:grid-cols-2 md:px-10 md:py-24"><div><p className="text-[10px] uppercase tracking-[.25em]">04 / Stay in touch</p><h2 className="mt-16 max-w-xl text-5xl leading-[.95] tracking-[-.07em] md:text-8xl">Less, but<br/><i className="font-serif font-normal">better.</i></h2></div><div className="flex flex-col justify-end md:items-end"><p className="mb-6 max-w-xs text-sm leading-6 text-white/60">New releases, studio notes and things worth keeping. In your inbox, occasionally.</p><div className="flex w-full max-w-sm border-b border-white/40 py-3"><input placeholder="Your email address" className="w-full bg-transparent text-sm outline-none placeholder:text-white/50"/><button aria-label="Subscribe"><ArrowRight/></button></div><p className="mt-5 text-[9px] uppercase tracking-[.2em] text-white/40">Instagram · Pinterest · hello@keshev.com</p></div></section>
    {cart.length > 0 && <aside className="fixed bottom-4 right-4 z-40 w-[calc(100%-2rem)] max-w-sm bg-white p-6 shadow-2xl"><div className="mb-6 flex items-center justify-between"><h3 className="text-xl tracking-tight">Your cart <span className="text-sm text-black/40">({cart.length})</span></h3><button onClick={() => setCart([])}><X size={18}/></button></div>{cart.map((p,i)=><div key={i} className="flex items-center gap-3 border-b border-black/10 py-3"><img src={p.image} className="h-14 w-12 object-cover"/><div className="flex-1"><p className="text-sm">{p.name}</p><p className="text-xs text-black/50">{p.price}</p></div></div>)}<div className="mt-6 flex justify-between text-sm"><span>Subtotal</span><span>₹{cart.reduce((sum,p)=>sum+Number(p.price.replace(/[^0-9]/g,'')),0).toLocaleString('en-IN')}</span></div><button className="mt-5 w-full bg-ink py-4 text-[10px] uppercase tracking-[.2em] text-white">Checkout securely</button></aside>}
  </main>
}
function ProductGrid({ items, onAdd }: { items: Product[], onAdd: (p: Product) => void }) { return <div className="grid gap-5 md:grid-cols-2">{items.map(p=><article key={p.name} className="group"><div className="relative aspect-[4/5] overflow-hidden bg-white"><img src={p.image} alt={p.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/>{p.tag && <span className="absolute left-4 top-4 bg-white px-3 py-2 text-[9px] uppercase tracking-[.2em]">{p.tag}</span>}<button onClick={() => onAdd(p)} className="absolute bottom-4 right-4 flex items-center gap-3 bg-white px-4 py-3 text-[9px] uppercase tracking-[.18em] opacity-0 transition group-hover:opacity-100">Quick add <ShoppingBag size={14}/></button></div><div className="flex justify-between pt-4 text-sm"><div><p>{p.name}</p><p className="mt-1 text-xs text-black/45">{p.type}</p></div><p>{p.price}</p></div></article>)}</div> }
