'use client'

import Link from 'next/link'
import { ArrowDownRight, ArrowRight } from 'lucide-react'
import Header from './components/Header'
import ProductShowcase from './components/ProductShowcase'
import { assetPath } from './lib/data'
import { useStore } from './components/StoreProvider'

export default function Home() {
  const {products}=useStore()
  return <main>
    <div className="intro-overlay" aria-hidden="true"><img src={assetPath('/brand/logo-black.png')} alt="" className="intro-mark intro-mark-dark"/><img src={assetPath('/brand/logo-white.png')} alt="" className="intro-mark intro-mark-light"/></div>
    <Header/>
    <section id="home" className="relative flex min-h-[92vh] items-end overflow-hidden bg-ink px-5 pb-10 text-white md:px-10 md:pb-14"><div className="grain absolute inset-0 opacity-80"/><div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-black/10"/><div className="relative w-full"><p className="mb-7 text-[10px] uppercase tracking-[.28em]">Independent label · Est. 2024</p><h1 className="display max-w-5xl">Made for<br/><i className="font-serif font-normal">every</i> day.</h1><div className="mt-10 flex flex-wrap gap-3"><a href="#tops" className="flex items-center gap-8 bg-white px-5 py-3 text-[10px] uppercase tracking-[.2em] text-ink">Explore tops <ArrowRight size={15}/></a><a href="#bottoms" className="flex items-center gap-8 border border-white/70 px-5 py-3 text-[10px] uppercase tracking-[.2em]">Explore bottoms <ArrowRight size={15}/></a></div></div></section>
    <section id="about" className="grid gap-12 px-5 py-24 md:grid-cols-[1fr_2fr] md:px-10 md:py-36"><p className="text-[10px] uppercase tracking-[.25em]">01 / The point of view</p><div><p className="max-w-3xl text-3xl leading-[1.08] tracking-[-.04em] md:text-6xl">A considered wardrobe for the everyday. <span className="text-black/35">No noise, no excess. Just pieces that get better with living in them.</span></p><Link href="/about" className="mt-10 inline-flex items-center gap-3 border-b border-ink pb-2 text-[10px] uppercase tracking-[.2em]">Read our story <ArrowDownRight size={15}/></Link></div></section>
    <section id="tops" className="bg-[#dcd7ce] px-5 py-16 md:px-10 md:py-24"><div className="mb-10 flex items-end justify-between"><div><p className="mb-3 text-[10px] uppercase tracking-[.25em]">02 / The collection</p><h2 className="text-5xl tracking-[-.07em] md:text-8xl">Tops</h2></div></div><ProductShowcase items={products.filter((product)=>product.collection==='Tops')}/></section>
    <section className="image-break" aria-label="Studio collection" style={{backgroundImage:"url('https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=2200&q=85')"}}><div className="flex min-h-[62vh] items-end bg-black/20 px-5 pb-10 text-white md:px-10"><p className="max-w-xl text-4xl leading-none tracking-[-.06em] md:text-7xl">Pieces that move<br/><i className="font-serif font-normal">with you.</i></p></div></section>
    <section id="bottoms" className="px-5 py-16 md:px-10 md:py-24"><div className="mb-10 flex items-end justify-between"><div><p className="mb-3 text-[10px] uppercase tracking-[.25em]">03 / The collection</p><h2 className="text-5xl tracking-[-.07em] md:text-8xl">Bottoms</h2></div></div><ProductShowcase items={products.filter((product)=>product.collection==='Bottoms')}/></section>
    <section id="support" className="grid min-h-[55vh] bg-ink px-5 py-16 text-white md:grid-cols-2 md:px-10 md:py-24"><div><p className="text-[10px] uppercase tracking-[.25em]">04 / Support and socials</p><h2 className="mt-16 max-w-xl text-5xl leading-[.95] tracking-[-.07em] md:text-8xl">Less, but<br/><i className="font-serif font-normal">better.</i></h2></div><div className="flex flex-col justify-end md:items-end"><p className="mb-6 max-w-xs text-sm leading-6 text-white/60">New releases, studio notes and things worth keeping. In your inbox, occasionally.</p><div className="flex w-full max-w-sm border-b border-white/40 py-3"><input placeholder="Your email address" className="w-full bg-transparent text-sm outline-none placeholder:text-white/50"/><button aria-label="Subscribe"><ArrowRight/></button></div><p className="mt-5 text-[9px] uppercase tracking-[.2em] text-white/40">Instagram · Pinterest · Contact</p><div className="mt-12 grid w-full max-w-sm grid-cols-2 gap-x-8 gap-y-4 border-t border-white/20 pt-5 text-[10px] uppercase tracking-[.18em] text-white/60"><Link href="/faq">FAQ</Link><Link href="/shipping">Shipping</Link><Link href="/returns">Returns</Link><Link href="/contact">Contact</Link><Link href="/wishlist">Wishlist</Link><Link href="/account">Account</Link></div></div></section>
  </main>
}
